# Generated by Django 3.2.6 on 2021-08-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('thumbnail', models.CharField(max_length=200)),
                ('network_technology', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('weight', models.PositiveIntegerField()),
                ('ip_rating', models.CharField(blank=True, max_length=4)),
                ('display_type', models.CharField(max_length=50)),
                ('display_refresh_rate', models.PositiveIntegerField()),
                ('display_size', models.DecimalField(decimal_places=2, max_digits=3)),
                ('screen_to_body_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('display_resolution', models.CharField(max_length=50)),
                ('display_protection', models.CharField(blank=True, max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=50)),
                ('card_slot', models.BooleanField(default=False)),
                ('camera_resolution', models.PositiveIntegerField()),
            ],
        ),
    ]
