# Generated by Django 3.2.6 on 2021-08-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('thumbnail', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Earbuds',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('battery_life', models.CharField(max_length=50)),
                ('battery_life_with_case', models.CharField(max_length=50)),
                ('bluetooth_version', models.CharField(max_length=50)),
                ('noise_cancelling', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3)),
            ],
            options={
                'verbose_name': 'Earbuds',
                'verbose_name_plural': 'Earbuds',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('battery_life', models.CharField(max_length=50)),
                ('bluetooth_version', models.CharField(max_length=50)),
                ('noise_cancelling', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3)),
            ],
            options={
                'verbose_name': 'Headphones',
                'verbose_name_plural': 'Headphones',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('internal_memory', models.CharField(max_length=50)),
                ('memory_card_support', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('memory_card_type', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('screen_size', models.CharField(max_length=50)),
                ('screen_resolution', models.CharField(max_length=50)),
                ('screen_type', models.CharField(max_length=50)),
                ('main_camera', models.CharField(blank=True, max_length=50)),
                ('selfie_camera', models.CharField(blank=True, max_length=50)),
                ('video_camera', models.CharField(max_length=50)),
                ('bluetooth', models.CharField(blank=True, max_length=50)),
                ('two_sim_card_support', models.CharField(blank=True, max_length=50)),
                ('sim_card_type', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('network_5g_bands', models.CharField(blank=True, max_length=200)),
                ('network_4g_bands', models.CharField(max_length=200)),
                ('network_3g_bands', models.CharField(max_length=200)),
                ('network_2g_bands', models.CharField(max_length=200)),
                ('wifi', models.CharField(max_length=50)),
                ('wifi_hotspot', models.CharField(blank=True, max_length=50)),
                ('body_dimensions', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('nfc', models.CharField(max_length=50)),
                ('usb_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Smartwatch',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('processor', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Smartwatch',
                'verbose_name_plural': 'Smartwatches',
            },
            bases=('shop.product',),
        ),
    ]
